#Lykasha's Prod for SQL database
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chinook
    username: root
    password: welcome1

logging:
  level:
    com:
      chinook: WARN